#设置启用环境
spring:
  profiles:
    active: ${profile.active}

---
#开发
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082

---
#生产
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 8083

---
#测试
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8084
